### ISSUE TITLE
RKE2 single node doesn't work for raw images

### ISSUE THREAD

**Issue by jdob** [suse-edge/edge-image-builder#147]
I successfully booted an ISO-based image built with the following:

```
apiVersion: 1.0
image:
  arch: x86_64
  imageType: iso
  baseImage: SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso
  outputImageName: ./out/eib-image.iso
kubernetes:
  version: v1.28.5+rke2r1
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$r2bo4ZUwh6Tnhi61$rTJJWWAaDB3Hk/NAkdJgFH26eJSE8NAIL/HjpO7Lunm0hQKNhvnKGEvoWMjduOIZKi4cB5KbOhEQZNjguLcMR/
```

I tried a raw image using the same kubernetes snippet on a raw image (the definition works without the snippet):

```
apiVersion: 1.0
image:
  arch: x86_64
  imageType: raw
  baseImage: SLE-Micro.x86_64-5.5.0-Default-GM.raw
  outputImageName: ./out/eib-image.raw
kubernetes:
  version: v1.28.5+rke2r1
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$r2bo4ZUwh6Tnhi61$rTJJWWAaDB3Hk/NAkdJgFH26eJSE8NAIL/HjpO7Lunm0hQKNhvnKGEvoWMjduOIZKi4cB5KbOhEQZNjguLcMR/
```

The VM fails to boot. I'm still trying to find an actual error on the VM, but this is what I see when it boots:

```
Domain 'eib-raw' started
Connected to domain 'eib-raw'
Escape character is ^] (Ctrl + ])

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


Press Enter for maintenance
(or press Control-D to continue):
```
