### ISSUE TITLE
Unattended install. is not unattended but asks for destroying all data on an empty disk

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#164]
Having the image config below, I would expect that the installation is indeed unattended. But it is asking for the destruction of the data. 

```
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso
  outputImageName: eib-image.iso
operatingSystem:
  isoInstallation:
    installDevice: /dev/sda
    unattended: true
```

![image](https://github.com/suse-edge/edge-image-builder/assets/139094/64a917a4-788b-49c4-ba48-3b74e7050069)
