### ISSUE TITLE
How to inject secrets into the Image Definition?

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#177]
I was wondering what a good approach would be on how to provide sensitive data to the image builder. For example the activationKey for SUMA?

Would it be possible to provide environment variables to the builder and that will be used in the processing of the template?

Something like below?

```yaml
  suma:
    host: suma.edge.suse.com
    activationKey: ${{ my-secret-activiation-key }}
```
