### ISSUE TITLE
[RFE] Add support for http(s) iso origins

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#238]
Currently EIB expects the ISO source image to be present in the filesystem but it would be nice to add support to provide an http(s) endpoint instead

```
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: http://foobar.example/SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso
  ...
```

This will probably require a certificate for https (or a `skipcertificate: true` var) as well as some kind of sha256 verification
