### ISSUE TITLE
Resolver breaks when specifing higher level versions for the RPM resolver.

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#271]
I am looking for a way to specify higher lever versions for the RPM resolver. 

Trying a package lists like below, `breaks the resolver`.  Or the open-driver cannot be found, or messages that there are conflicts.

```
# trying to resolve all dependencies that work with the specified driver version
packages:
    noGPGCheck: true
    packageList:

      - nvidia-open-driver-G06-signed-kmp-default=545.29.06
      - nvidia-compute-utils-G06
      - nvidia-gl-G06
      - nvidia-container-toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp5/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
```

```
# trying to resolve all dependencies that work with compute utils
packages:
    noGPGCheck: true
    packageList:

      - nvidia-open-driver-G06-signed-kmp-default
      - nvidia-compute-utils-G06=545.29.06
      - nvidia-gl-G06
      - nvidia-container-toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp5/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
```

```
# trying to specify higher level versions for all dependencies
packages:
    noGPGCheck: true
    packageList:

      - nvidia-open-driver-G06-signed-kmp-default=545.29.06
      - nvidia-compute-utils-G06=545.29.06
      - nvidia-gl-G06=545.29.06
      - nvidia-container-toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp5/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
```

Example output of the logs:

In the case below I fixed the version of compute utils but it still want to installs the latest driver that is not compatible.

```
Resolving package dependencies...

Problem: nothing provides 'kernel-azure' needed by the to be installed nvidia-driver-G06-kmp-azure-545.29.06_k5.14.21_150500.31-150500.19.1.x86_64
 Solution 1: Following actions will be done:
  do not install nvidia-gl-G06-545.29.06-150500.19.1.x86_64
  do not install nvidia-compute-utils-G06-545.29.06-150500.19.1.x86_64
 Solution 2: do not install nvidia-open-driver-G06-signed-kmp-default-550.54.14_k5.14.21_150500.55.49-150500.3.36.1.x86_64
 Solution 3: break nvidia-driver-G06-kmp-azure-545.29.06_k5.14.21_150500.31-150500.19.1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c/d/?] (c): c
```

I tried the corresponding installs using Leap Micro (zypper) and there it seems to work well. So wondering what I am missing or doing wrong :)?
