### ISSUE TITLE
Cilium operator pod stuck in `Pending` state

### ISSUE THREAD

**Issue by ipetrov117** [suse-edge/edge-image-builder#301]
## Problem
When booting an EIB image with a configured single-node Kubernetes cluster, one of the two Cilium operator pods that are deployed gets stuck in a `Pending` state.

The pods:
```bash
localhost:~ # k get pods -A
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   cilium-mwxcn                                            1/1     Running     0          101m
kube-system   cilium-operator-558bbf6cfd-49zc6                        1/1     Running     0          101m
kube-system   cilium-operator-558bbf6cfd-x6g7j                        0/1     Pending     0          101m
kube-system   cloud-controller-manager-localhost.localdomain          1/1     Running     0          101m
kube-system   etcd-localhost.localdomain                              1/1     Running     0          101m
...
```

`Pending` pod description:
```bash
localhost:~ # k describe pod cilium-operator-558bbf6cfd-x6g7j -n kube-system
Name:                 cilium-operator-558bbf6cfd-x6g7j
Namespace:            kube-system
...
Status:               Pending
...
Containers:
  cilium-operator:
    Image:      rancher/mirrored-cilium-operator-generic:v1.15.1
    Port:       9963/TCP
    Host Port:  9963/TCP
    Command:
      cilium-operator-generic
...
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  15m (x21 over 101m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports..

```

Describe of the `Running` pod:
```bash
localhost:~ # k describe pod cilium-operator-558bbf6cfd-49zc6 -n kube-system
Name:                 cilium-operator-558bbf6cfd-49zc6
Namespace:            kube-system
...
Status:               Running
...
Containers:
  cilium-operator:
    Container ID:  containerd://7cb6e9981f623de6bbf342b30b4d43d1de9d4e6684641f6ed4e99bd6a24c3063
    Image:         rancher/mirrored-cilium-operator-generic:v1.15.1
    Image ID:      sha256:46ff2cc7ee013670e45ab9f3381896f67c2832f53782176ec7e052ad41ce8a0c
    Port:          9963/TCP
    Host Port:     9963/TCP
    Command:
      cilium-operator-generic
...
Events:                      <none>
```

The problem here seems to be that `cilium-operator-558bbf6cfd-49zc6` is running on port `9963`. `cilium-operator-558bbf6cfd-x6g7j` also attempts to run on `9963`, but since the port is already taken it gets stuck in a `Pending` state. Why do we need 2 pods running on the same port, is it a configuration that I missed on my side?

## Environment where this was produced

Host where EIB image is built:
```bash
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

EIB definition file:
```yaml
apiVersion: 1.0
image:
  imageType: raw
  arch: x86_64
  baseImage: SLE-Micro.x86_64-5.5.0-Default-RT-GM.raw
  outputImageName: eib-image.raw
operatingSystem:
  users:
  - username: root
    encryptedPassword: $6$djShT68COdFybrdw$n8EgYB.ZTRpauS70luGpW.VKIedBIdCMjnfsKXhJBYX.75RgZU1jk3E4k9qd13RjKu/qws.h4fEbr8SLFLAw21
  rawConfiguration:
    diskSize: 20G
kubernetes:
  version: v1.28.7+rke2r1
```

EIB image build command:
```bash
sudo podman run --rm --privileged -it -v <eib_dir_path>:/eib eib:dev build -definition-file <definition_file>.yaml -config-dir /eib -build-dir /eib/_build
```
