### ISSUE TITLE
xorriso only create a combustion.iso when image base does not exists

### ISSUE THREAD

**Issue by alknopfler** [suse-edge/edge-image-builder#33]
Description:
- having this config (take a look is default without RT):
```
apiVersion: 1.0
image:
  imageType: iso
  baseImage: SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso
  outputImageName: eib-image-slemicro55.iso
```
but using the image base with -RT for real time kernel into the images folder
```
$ ls
SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM.install.iso
```
the script xorriso is creating the combustion successfully but adding to no image, so the script is not failing but it's not creating the final image.

I think a validation step is required to ensure the image present on the /images folder is the same than the config yaml file image.
