### ISSUE TITLE
[RFE] Expose the ingress via metallb when deployed (optionally?)

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#330]
The nginx ingress can use metallb to expose apps outside of the cluster (otherwise it just uses nodeport or hostport by default https://docs.rke2.io/networking#nginx-ingress-controller)
If you want to expose apps using ingress via metallb, the nginx ingress controller configuration needs to be modified as:

* Add helmchartconfig for nginx-ingress to create the service of loadbalancer type. I'm using this one:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
      publishService:
        enabled: true
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
```
* Deploy both ipadresspool and l2adv (or bgp) for that ip
```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ippool
  namespace: kube-system
spec:
  addresses:
  - 192.168.122.11/32
  serviceAllocation:
    priority: 100
    serviceSelectors:
    - matchExpressions:
      - {key: app.kubernetes.io/name, operator: In, values: [rke2-ingress-nginx]}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-l2-adv
  namespace: kube-system
spec:
  ipAddressPools:
  - ingress-ippool
```

Bear in mind those are just example files (that I stole from https://blog.monotok.org/posts/rke2-k8s-nginx-ingress-metallb-pfsense/#nginx-ingress-controller)

**Comment by e-minguez** [comment]
```
host1rke2:~ # k get svc -n kube-system rke2-ingress-nginx-controller
NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
rke2-ingress-nginx-controller   LoadBalancer   10.43.190.101   192.168.122.11   80:30673/TCP,443:32738/TCP   3m24s
host1rke2:~ # k get ingress -n cattle-system
NAME      CLASS    HOSTS                             ADDRESS          PORTS     AGE
rancher   <none>   rancher-192.168.122.11.sslip.io   192.168.122.11   80, 443   69m
host1rke2:~ # curl -LkI https://rancher-192.168.122.11.sslip.io
HTTP/2 200
date: Fri, 22 Mar 2024 14:40:36 GMT
content-type: application/json
cache-control: no-cache, no-store, must-revalidate
expires: Wed 24 Feb 1982 18:42:00 GMT
x-api-cattle-auth: false
x-api-schemas: https://rancher-192.168.122.11.sslip.io/meta/schemas
x-content-type-options: nosniff
strict-transport-security: max-age=15724800; includeSubDomains
```

**Comment by rdoxenham** [comment]
I made further progress on this via Edge Image Builder. Adding in here so we don't lose it, and suggest that we either add it to the docs, or add in an `ingressVIP` option into the image definition.

Setting up the ingress VIP:

```
% cat kubernetes/manifests/ingress-vip.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ip
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.200/32
  avoidBuggyIPs: true
  serviceAllocation:
    namespaces:
      - kube-system
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-ip-l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-ip
```

Modifying the RKE2 ingress configuration to specify the VIP:

```
% cat os-files/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
      publishService:
        enabled: true
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.122.200
```

Modifying the Rancher Helm values to set the desired ingress hostname:

```
% cat kubernetes/helm/values/rancher-values.yaml
hostname: rancher.ingress.cluster01.edge.suse.com
replicas: 3
bootstrapPassword: "adminadminadmin"
systemDefaultRegistry: registry.rancher.com
useBundledSystemChart: true
```

Kubernetes section of EIB configuration:

```
kubernetes:
  version: v1.30.5+rke2r1
  network:
    apiVIP: 192.168.122.100
    apiHost: api.cluster01.edge.suse.com
  nodes:
    - hostname: node1.edge.suse.com
      type: server
    - hostname: node2.edge.suse.com
      type: server
    - hostname: node3.edge.suse.com
      type: server
  manifests:
    urls:
    - https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.crds.yaml
  helm:
    charts:
      - name: rancher
        version: 2.9.3
        repositoryName: rancher-prime
        valuesFile: rancher-values.yaml
        targetNamespace: cattle-system
        createNamespace: true
        installationNamespace: kube-system
      - name: cert-manager
        installationNamespace: kube-system
        createNamespace: true
        repositoryName: jetstack
        targetNamespace: cert-manager
        version: 1.15.3
    repositories:
      - name: jetstack
        url: https://charts.jetstack.io
      - name: rancher-prime
        url:  https://charts.rancher.com/server-charts/prime
```

**Comment by rdoxenham** [comment]
I made further progress on this via Edge Image Builder. Adding in here so we don't lose it, and suggest that we either add it to the docs, or add in an `ingressVIP` option into the image definition.

Setting up the ingress VIP:

```
% cat kubernetes/manifests/ingress-vip.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-ip
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.200/32
  avoidBuggyIPs: true
  serviceAllocation:
    namespaces:
      - kube-system
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-ip-l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-ip
```

Modifying the RKE2 ingress configuration to specify the VIP:

```
% cat os-files/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
      publishService:
        enabled: true
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.122.200
```

Modifying the Rancher Helm values to set the desired ingress hostname:

```
% cat kubernetes/helm/values/rancher-values.yaml
hostname: rancher.ingress.cluster01.edge.suse.com
replicas: 3
bootstrapPassword: "supersecretadminpassword"
systemDefaultRegistry: registry.rancher.com
useBundledSystemChart: true
```

Kubernetes section of EIB configuration:

```
kubernetes:
  version: v1.30.5+rke2r1
  network:
    apiVIP: 192.168.122.100
    apiHost: api.cluster01.edge.suse.com
  nodes:
    - hostname: node1.edge.suse.com
      type: server
    - hostname: node2.edge.suse.com
      type: server
    - hostname: node3.edge.suse.com
      type: server
  manifests:
    urls:
    - https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.crds.yaml
  helm:
    charts:
      - name: rancher
        version: 2.9.3
        repositoryName: rancher-prime
        valuesFile: rancher-values.yaml
        targetNamespace: cattle-system
        createNamespace: true
        installationNamespace: kube-system
      - name: cert-manager
        installationNamespace: kube-system
        createNamespace: true
        repositoryName: jetstack
        targetNamespace: cert-manager
        version: 1.15.3
    repositories:
      - name: jetstack
        url: https://charts.jetstack.io
      - name: rancher-prime
        url:  https://charts.rancher.com/server-charts/prime
```
