### ISSUE TITLE
build raw aarch64 failed : libguestfs

### ISSUE THREAD

**Issue by fafarun** [suse-edge/edge-image-builder#333]
I try to build a raw image for the aarch64 archi. 
But the build failed with this error log 
``` 
*stdin*:2: libguestfs: error: sh: /bin/sh: Exec format error
```

Here my config file : 
I have the same error for sles raw file. 
``` 
apiVersion: 1.0
image:
  arch: aarch64
  imageType: raw
  baseImage: openSUSE-MicroOS.aarch64-RaspberryPi.raw
  outputImageName: ./out/basic.raw
operatingSystem:
  users:
    - username: root
      encryptedPassword: $6$r2bo4ZUwh6Tnhi61$rTJJWWAaDB3Hk/NAkdJgFH26eJSE8NAIL/HjpO7Lunm0hQKNhvnKGEvoWMjduOIZKi4cB5KbOhEQZNjguLcMR/
```

I did it from this os : 
```
6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

I have to be on a aarch64 linux to build this type of raw ?
