### ISSUE TITLE
Error when trying to build an image with noGPGCheck: true and Suse Manager VENV as side loaded RPM

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#348]
When building a simple image that contains a side loaded rpm for Suse Manager an error is thrown.

```yaml
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso
  outputImageName: build-image.iso
operatingSystem:
  suma:
    host: ***
    activationKey: ***
  packages:
    noGPGCheck: true
```

```
2024-03-31T18:20:15.965Z	FATAL	build/build.go:102	An error occurred building the image: configuring combustion: configuring component "RPM": describing GPG directory at '/eib/rpms/gpg-keys': stat /eib/rpms/gpg-keys: no such file or directory
github.com/suse-edge/edge-image-builder/pkg/cli/build.Run
	/src/pkg/cli/build/build.go:102
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*App).RunContext
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337
github.com/urfave/cli/v2.(*App).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main
	/src/cmd/eib/main.go:19
runtime.main
	/usr/lib64/go/1.22/src/runtime/proc.go:271
```

The files are in the respective rpms folder and certificate

```
image-config/rpms/venv-salt-minion-3006.0-150000.3.45.4.x86_64.rpm
image-config/certificates/RHN-ORG-TRUSTED-SSL-CERT.pem

```
