### ISSUE TITLE
Kernel parameters not applied on boot/reboot

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#375]
I am trying to harden a K3s installation and according to the documentation I need to provide some kernel parameters. 

The current image config has the following parameters:
```yaml
operatingSystem:
  kernelArgs:
    - fips=1
    - vm.panic_on_oom=0
    - vm.overcommit_memory=1
    - kernel.panic=10
    - kernel.panic_on_oops=1
```

When booting the image the kernel  parameters seem not to be applied. They seem not to be set when checking with `sysctl -a | grep <param>`

```
$ sysctl -a | grep kernel.panic
kernel.panic = 0 # expect 10
kernel.panic_on_oops = 0 # expect 1
```

However the params are nicely in the `/proc/cmdline`
```
$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.14.21-150500.55.19-default root=UUID=e2935bc6-aa22-443b-8331-578c5c575ac7 rd.timeout=60 console=ttyS0,115200 console=tty0 security=selinux selinux=1 quiet net.ifnames=0 ignition.firstboot dasd_mod.dasd=autodetect ignition.platform.id=metal fips=1 vm.panic_on_oom=0 vm.overcommit_memory=1 kernel.panic=10 kernel.panic_on_oops=1
```

I wonder what I am doing wrong?
