### ISSUE TITLE
installDevice option is not working in Leap Micro

### ISSUE THREAD

**Issue by orangedeng** [suse-edge/edge-image-builder#395]
Components:

- Leap Micro: 5.5 SelfInstall
- EIB: 1.0.0.rc3

Following is the definition file:

```yaml
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: micro.iso
  outputImageName: eib-image.iso
operatingSystem:
  isoConfiguration:
    installDevice: /dev/sda
  users:
    - username: root
      encryptedPassword: $6$NEi4Y1pauz2Ya9gy$QUBRl/YkPgUyiJ41Iw9Zho7ngoWxbhTQL2U/ahB3b7iXmAOBc1xqw4RabfYs/2SfCo6EWi4Sg8avnczEkDjRk0
```

After boot from the ISO, I still needs to select install disk:
![截屏2024-04-16 17 06 12](https://github.com/suse-edge/edge-image-builder/assets/15376837/687bd73e-529c-4b7f-a8b5-1e6833c884d0)
