### ISSUE TITLE
Bug: Method of discovering required container images is not robust

### ISSUE THREAD

**Issue by koendelaat** [suse-edge/edge-image-builder#442]
The current way of determining the required container images is not robust and causes crashes of the EIB for certain helm charts. (https://github.com/suse-edge/edge-image-builder/blob/main/pkg/registry/manifests.go#L87)

```yaml
kubernetes:
  helm:
    repositories:
      - name: nvidia
        url: https://helm.ngc.nvidia.com/nvidia
    charts:
      - name: gpu-operator
        repositoryName: nvidia
        version: v23.9.2
        targetNamespace: gpu-operator
        createNamespace: true
        installationNamespace: kube-system
        valuesFile: gpu-operator.yaml
```

This results in:
```
2024-05-14T09:32:36.687Z	INFO	combustion/registry.go:342	Adding the following images to the embedded artifact registry:
[gpu-feature-discovery dcgm k8s-device-plugin registry.k8s.io/nfd/node-feature-discovery:v0.14.2 k8s-mig-manager  kubevirt-gpu-device-plugin driver k8s-kata-manager vgpu-manager container-toolkit dcgm-exporter gpu-operator-validator cuda nvcr.io/nvidia/gpu-operator:v23.9.2 k8s-driver-manager k8s-cc-manager vgpu-device-manager]
2024-05-14T09:32:49.577Z	FATAL	build/build.go:102	An error occurred building the image: configuring combustion: configuring component "embedded artifact registry": configuring embedded artifact registry: populating registry: adding image to hauler: running hauler add image command: exit status 1: 
github.com/suse-edge/edge-image-builder/pkg/cli/build.Run
	/src/pkg/cli/build/build.go:102
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:276
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:269
github.com/urfave/cli/v2.(*App).RunContext
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:333
github.com/urfave/cli/v2.(*App).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:307
main.main
	/src/cmd/eib/main.go:19
runtime.main
	/usr/lib64/go/1.22/src/runtime/proc.go:271
```
