### ISSUE TITLE
Support images.txt for the Embedded Artifact Registry

### ISSUE THREAD

**Issue by dgiebert** [suse-edge/edge-image-builder#444]
Rancher and a lot of the components provide a list of images.txt files e.g.
- https://github.com/k3s-io/k3s/releases/download/v1.30.0%2Bk3s1/k3s-images.txt
- https://github.com/rancher/rke2/releases/download/v1.30.0%2Brke2r1/rke2-images-all.linux-amd64.txt

```yaml 
embeddedArtifactRegistry:
  imageList:
  - url: https://github.com/k3s-io/k3s/releases/download/v1.30.0%2Bk3s1/k3s-images.txt
  - url: https://github.com/rancher/rke2/releases/download/v1.30.0%2Brke2r1/rke2-images-all.linux-amd64.txt
  images:
  - name: hello-world:latest
```

This would make it a lot easier to pre-pull the images for elemental installations
