### ISSUE TITLE
Large Helm manifests unable to install

### ISSUE THREAD

**Issue by koendelaat** [suse-edge/edge-image-builder#491]
Related to #477 

Large Helm charts are unable to install due to used install mechanism:

```
$ kubectl apply -f ARTEFACTS/KUBERNETES/MANIFESTS/KUBE_PROMETHEUS_STACK.YAML
The HelmChart "kube-prometheus-stack" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

Suggested solution:

```
$ kubectl create -f ARTEFACTS/KUBERNETES/MANIFESTS/KUBE_PROMETHEUS_STACK.YAML
helmchart.helm.cattle.io/kube-prometheus-stack created
```

Used config:
```yaml
kubernetes:
  helm:
    repositories:
      - name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
    charts:
      - name: kube-prometheus-stack
        repositoryName: prometheus-community
        version: v59.0.0
        targetNamespace: prometheus
        createNamespace: false
        installationNamespace: kube-system
        valuesFile: kube-prometheus-stack.yaml

```

kube-prometheus-stack.yaml
```yaml
grafana:
  enabled: false

alertmanager:
  enabled: false

defaultRules:
  create: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
```
