### ISSUE TITLE
kernelArgs broken with Leap Micro 6.0

### ISSUE THREAD

**Issue by hardys** [suse-edge/edge-image-builder#498]
I'm trying to build a raw image with a configuration that worked for 5.5 e.g:

```
apiVersion: 1.0
image:
  imageType: raw
  arch: x86_64
  baseImage: openSUSE-Leap-Micro.x86_64-6.0-Default-Build22.15.raw
  outputImageName: openSUSE-Leap-Micro.x86_64-6.0-Default-Build22.15.metal3.raw
operatingSystem:
  kernelArgs:
  - ignition.platform.id=openstack
  - net.ifnames=1
```

I built a local container image based on 058860173952a654f4ada0afc905339b93b07c31 which builds the image without errors but when booting the image we don't see the cmdline args added:

```
controlplane-0:~ # cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-6.4.0-17-default root=UUID=7429bc86-6e9b-4d30-ad99-4c620001b3fa rd.timeout=60 rd.retry=45 console=ttyS0,115200 console=tty0 security=selinux selinux=1 quiet net.ifnames=0
1
```

It seems this may be a similar issue to https://github.com/suse-edge/edge-image-builder/issues/487 but it's impacting the deployed image, not the install device for the installer iso
