### ISSUE TITLE
Package install breaks package resolution if packages is already installed on root OS

### ISSUE THREAD

**Issue by ipetrov117** [suse-edge/edge-image-builder#594]
There is a corner-case where a user can provide a `base-image` that has some packages already installed on it. 

If the user (or EIB) then defines the same package version for installation in the `definition file`, the RPM resolution process breaks with the following error:

```bash
touch: cannot touch '/tmp/rpm-repo/zypper-success': No such file or directory
```

This is happening due to the fact that the [zypper install](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/rpm/resolver/templates/rpm-resolution.sh.tpl#L41) command does not create the `--pkg-cache-dir` directory if it did not download any new packages. Which is the case in this corner-case..

A real life example of the problem would be:

1. User provides a base image that has the `elemental-register` and `elemental-system-agent` packages already installed
2. User starts an EIB image build with the elemental component enabled
3. EIB tries to automatically add the `elemental-register` and `elemental-system-agent` packages for installation as part of the RPM component
4. RPM resolution breaks because the `/tmp/rpm-repo` directory is not created, because `zypper install` did not find any new package versions for installation

**_Steps to reproduce the problem:_**

Since it would be tedious to reproduce the "real life" example, you can use a simplified version that just tries to deploy a version of `curl` that already exists on the `base-image`.

Using this `definition file`: 

```yaml
apiVersion: 1.0
image:
  imageType: raw
  arch: x86_64
  baseImage: SL-Micro.x86_64-6.0-Base-GM.raw
  outputImageName: eib-cluster-longhorn.raw
operatingSystem:
  users:
  - username: root
    encryptedPassword: $6$djShT68COdFybrdw$n8EgYB.ZTRpauS70luGpW.VKIedBIdCMjnfsKXhJBYX.75RgZU1jk3E4k9qd13RjKu/qws.h4fEbr8SLFLAw21
  rawConfiguration:
    diskSize: 20G
  systemd:
    disable:
      - rebootmgr
  packages:
    noGPGCheck: true
    packageList:
      - curl-8.6.0-1.2
    sccRegistrationCode: INTERNAL-USE-ONLY-change-me
```

We get the following error from the RPM component:

_podman-image-build.log:_
```bash
...
Reading installed packages...
'curl = 8.6.0-1.2' is already installed.
There is an update candidate 'curl-8.6.0-2.1.x86_64' for 'curl-8.6.0-1.2.x86_64', but it does not match the specified version, architecture, or repository.
Resolving package dependencies...
Nothing to do.
touch: cannot touch '/tmp/rpm-repo/zypper-success': No such file or directory
```

Please note the problem is not with the `zapper-success`, but with the missing directory, even if `zypper-success` is missing the following commands (podman cp, etc.) related to the resolution process will fail.
