### ISSUE TITLE
Nvidia support is broken or docs are inaccurate

### ISSUE THREAD

**Issue by PidgeyBE** [suse-edge/edge-image-builder#613]
Hi

I'm trying to evaluate EIB on a device with NVIDIA GPU.
I've followed this guide https://documentation.suse.com/suse-edge/3.0/html/edge/id-nvidia-gpus-on-sle-micro.html#id-bringing-it-together-via-edge-image-builder to come to this `definition.yaml`:
```
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: SL-Micro.x86_64-6.0-Default-SelfInstall-GM2.install.iso
  outputImageName: rv-release-5-nvidia.iso

operatingSystem:
  packages:
    packageList:
      - nvidia-open-driver-G06-signed-kmp-default # the nvidia videcard driver
      - nvidia-compute-utils-G06 # cuda utils / libraries
      - nvidia-gl-G06 # opengl support
      - nvidia-container-toolkit # container toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp5/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
    sccRegistrationCode: XXXX
kubernetes:
  version: v1.29.7+k3s1
  helm:
    charts:
      - name: nvidia-device-plugin
        version: v0.14.5
        installationNamespace: kube-system
        targetNamespace: nvidia-device-plugin
        createNamespace: true
        valuesFile: nvidia-device-plugin.yaml
        repositoryName: nvidia
    repositories:
      - name: nvidia
        url: https://nvidia.github.io/k8s-device-plugin
```

However, when I try to build an ISO using this configuration, the build fails:
`eib-build.log`
```
2024-11-19T10:49:14.913Z	FATAL	build/build.go:88	An error occurred building the image: configuring image: configuring component "RPM": resolving rpm/package dependencies: building resolver image: building image from context /eib/_build/build-Nov19_10-31-17/resolver-image-build: building at STEP "RUN ./rpm-resolution.sh": while running runtime: exit status 4
```

`podman-image-build.log`
```
Resolving package dependencies...
2 Problems:
Problem: nothing provides 'kernel-azure' needed by the to be installed nvidia-driver-G06-kmp-azure-550.127.05_k5.14.21_150500.31-150500.27.1.x86_64
Problem: nothing provides 'libOpenCL1' needed by the to be installed nvidia-compute-G06-550.127.05-150500.27.1.x86_64

Problem: nothing provides 'kernel-azure' needed by the to be installed nvidia-driver-G06-kmp-azure-550.127.05_k5.14.21_150500.31-150500.27.1.x86_64
 Solution 1: do not install nvidia-gl-G06-550.127.05-150500.27.1.x86_64
 Solution 2: break nvidia-driver-G06-kmp-azure-550.127.05_k5.14.21_150500.31-150500.27.1.x86_64 by ignoring some of its dependencies
```

Am I looking to the wrong docs?
What is the correct way to enable NVIDIA in k3s using EIB?

Thanks! Pj

**Comment by atanasdinov** [comment]
Hello! You're trying to build an SL Micro 6.0 image which means that you should use the relevant Edge 3.1 / SL Micro 6.0 sources. Please try to follow the [respective docs](https://documentation.suse.com/suse-edge/3.1/html/edge/id-nvidia-gpus-on-sle-micro.html#id-bringing-it-together-via-edge-image-builder) and let us know if you're still encountering issues. 

As a general rule of a thumb, I'd suggest to follow the "manual" steps first. Once you confirm that the setup is working as expected, you can proceed with automating it via EIB.

**Comment by PidgeyBE** [comment]
@atanasdinov Thank you for the quick reply!
Indeed, I was looking at old docs. There is one difference with the newer ones:
```
-       - url: https://download.nvidia.com/suse/sle15sp5/
+      - url: https://download.nvidia.com/suse/sle15sp6/
```

Unfortunately the issue/errors remain the same after updating the package repository URL...

**Comment by PidgeyBE** [comment]
The "manual steps" fail in the same way
```
transactional-update shell
zypper ar https://download.nvidia.com/suse/sle15sp6/ nvidia-sle15sp6-main

zypper --gpg-auto-import-keys refresh
zypper search-packages nvidia-open-driver
SUSEConnect --product SL-Micro/6.0/x86_64 -r XXXXX

zypper install -y --auto-agree-with-licenses nvidia-open-driver-G06-signed-kmp nvidia-compute-utils-G06
```

--> 

```
Refreshing service 'SUSE_Linux_Micro_6.0_x86_64'.

Building repository 'SL-Micro-6.0-Pool' cache .....................................................[done]
Loading repository data...
Reading installed packages...
'nvidia-open-driver-G06-signed-kmp' not found in package names. Trying capabilities.
Resolving package dependencies...

Problem: nothing provides 'libOpenCL1' needed by the to be installed nvidia-compute-G06-550.127.05-150600.27.1.x86_64
 Solution 1: do not install nvidia-compute-utils-G06-550.127.05-150600.27.1.x86_64
 Solution 2: break nvidia-compute-G06-550.127.05-150600.27.1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): c
```

**Comment by PidgeyBE** [comment]
Using manual steps and some trial & error I found the following configuration to be working:
```
    packageList:
      - nvidia-open-driver-G06-signed-kmp-default=550.54.14_k6.4.0_17-1.15  # the nvidia videcard driver
      - nvidia-compute-utils-G06=550.54.14 # cuda utils / libraries
      - nvidia-gl-G06=550.54.14 # opengl support
      - nvidia-container-toolkit # container toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp6/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
```
