### ISSUE TITLE
k3s does not start in airgapped set up

### ISSUE THREAD

**Issue by PidgeyBE** [suse-edge/edge-image-builder#622]
Hi

When deploying k3s via EIB, k3s will not start if there is no ethernet cable plugged in into the device.
This results in:
```
[FAILED] Failed to start Network Manager Wait Online.
[FAILED] Failed to start Lightweight Kubernetes.
```
When inspecting `journalctl -u k3s` I see
`level=fatal msg="no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"`

Am I doing something wrong or is EIB not made to be used in fully airgapped situations?
Even if I install the same ISO on a device with ethernet cable plugged in, I get the same issues on first boot. After rebooting, k3s does start.

BR, Pj

**Comment by atanasdinov** [comment]
Hello! EIB is definitely meant to be used in airgapped environments. It will, however, not assume there's a missing network. One of the main requirements for both k3s and RKE2 is to have a default route set up -- please see https://docs.k3s.io/installation/airgap#default-network-route.

There are numerous ways of configuring the network with EIB, please check our [official docs](https://documentation.suse.com/suse-edge/3.1/html/edge/components-nmc.html#id-configuring-with-edge-image-builder) to figure out what's the proper approach for your use case.

**Comment by jdob** [comment]
@PidgeyBE If you're comfortable with Atanas' answer, can you please close out the issue?

**Comment by PidgeyBE** [comment]
Definitely!

I've been using the information shared by Atanas to try to come to a working setup, but unfortunately I haven't succeeded yet.
A sample configuration of how to exactly configure EIB to have a dummy network interface would be very helpful.

**Comment by atanasdinov** [comment]
You can follow the [custom configuration](https://documentation.suse.com/suse-edge/3.1/html/edge/components-nmc.html#id-custom-network-configurations) e.g. something along the lines of:
```
mkdir -p $CONFIG_DIR/network

cat << EOF > $CONFIG_DIR/network/configure-network.sh
#!/bin/bash
set -eux

ip link add dummy0 type dummy
ip link set dummy0 up
ip addr add 203.0.113.254/31 dev dummy0
ip route add default via 203.0.113.255 dev dummy0 metric 1000
EOF

chmod a+x $CONFIG_DIR/network/configure-network.sh
```

This will use the "custom network script" functionality of EIB which in turn executes the example from the k3s docs about a dummy route. I haven't tested it but I'd expect this to work.

**Comment by PidgeyBE** [comment]
Yeah, I've tried something similar before, but it didnt work.
Reproduced the issue with your example:

![image](https://github.com/user-attachments/assets/2712d399-3534-47a7-8696-d4f9bc87b2f1)

**Comment by atanasdinov** [comment]
Can you show the output of these two:
1. `journalctl -u combustion-prepare`
2. `journalctl -u combustion`

These are first things to check when there's a failure in the boot process.

**Comment by PidgeyBE** [comment]
Thanks, good to know!
Seems like it doesn't know the device type `dummy`...
![image](https://github.com/user-attachments/assets/c71118ca-b2a2-4709-a1c7-b8817d6c3a04)

**Comment by PidgeyBE** [comment]
I fixed this by creating `network/_all.yaml` with:
```
interfaces:
  - name: eth0
    type: ethernet
    state: up
    ipv4:
      enabled: true
      dhcp: true
  - name: dummy0
    type: dummy
    state: up
    ipv4:
      enabled: true
      address:
        - ip: 203.0.113.254
          prefix-length: 31
routes:
  config:
    - destination: 0.0.0.0/0
      next-hop-address: 203.0.113.255
      next-hop-interface: dummy0
      metric: 2000
```
That works.

Although, in case a network cable _is_ connected, the `eth0` does not get an IP address on first boot. On second boot the interface works...
So that's still a remaining issue
