### ISSUE TITLE
Combustion files are rendered with unneeded blank spaces

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#66]
This simple config file renders an add-users.sh file with too much blank spaces:

```
eminguez@lima-default:~> cat eib/config-eib.yaml
apiVersion: 1.0
image:
  imageType: raw
  baseImage: SLE-Micro.x86_64-5.5.0-Default-GM.raw
  outputImageName: SLEMicro.x86_64--5.5.0-Default-GM-userpass-openstack.raw
operatingSystem:
  kernelArgs:
  - ignition.platform.id=openstack
  users:
  - username: root
    password: foobar


eminguez@lima-default:~> cat eib/_build/combustion/add-users.sh
#!/bin/bash
set -euo pipefail

# Without this, the script will run successfully during combustion, but when /home
# is mounted it will hide the /home used during these user creations.
mount /home









    echo 'root:foobar' | chpasswd -e





```

I think this is because go templating doesn't remove them but I'm not a golang expert.
