### ISSUE TITLE
[Feature Request] Support `kustomize` in the Kubernetes configuration section

### ISSUE THREAD

**Issue by jizusun** [suse-edge/edge-image-builder#664]
We want to include the [rancher/system-upgrade-controller](https://github.com/rancher/system-upgrade-controller/tree/master) in our image, but I found only `manifests` and `helm` is supported.
https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#kubernetes

Does it make sense to support kustomize in the Kubernetes configuration section?

**Comment by e-minguez** [comment]
Just in case, s-u-c can be deployed via a Helm Chart located here https://github.com/rancher/charts/blob/dev-v2.10/charts/system-upgrade-controller/105.0.1/Chart.yaml 
We also recommend deploying s-u-c via our fleet manifests https://documentation.suse.com/suse-edge/3.1/html/edge/components-system-upgrade-controller.html#components-system-upgrade-controller-install

**Comment by jizusun** [comment]
> Just in case, s-u-c can be deployed via a Helm Chart located here https://github.com/rancher/charts/blob/dev-v2.10/charts/system-upgrade-controller/105.0.1/Chart.yaml We also recommend deploying s-u-c via our fleet manifests https://documentation.suse.com/suse-edge/3.1/html/edge/components-system-upgrade-controller.html#components-system-upgrade-controller-install

Thank you so much  @e-minguez  

And actually plain manifests should work right?

```yaml
  manifests:
    urls:
      - https://github.com/rancher/system-upgrade-controller/raw/refs/tags/v0.15.1/manifests/clusterrole.yaml
      - https://github.com/rancher/system-upgrade-controller/raw/refs/tags/v0.15.1/manifests/clusterrolebinding.yaml
      - https://github.com/rancher/system-upgrade-controller/raw/refs/tags/v0.15.1/manifests/system-upgrade-controller.yaml
```
