### ISSUE TITLE
Unable to install large Helm Chart defined in Edge Image Builder

### ISSUE THREAD

**Issue by koendelaat** [suse-edge/edge-image-builder#669]
For full investigation see: https://github.com/k3s-io/helm-controller/issues/267

This HelmChart resourse is created using:

```yaml
kubernetes:
  helm:
    repositories:
      - name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
    charts:
      -name: kube-prometheus-stack
        repositoryName: prometheus-community
        version: 69.8.2
        targetNamespace: prometheus
        createNamespace: false
        installationNamespace: kube-system
        valuesFile: kube-prometheus-stack.yaml

```
