### ISSUE TITLE
add-users.sh should have encrypted passwords instead of plain ones

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#67]
```
eminguez@lima-default:~> cat eib/config-eib.yaml
apiVersion: 1.0
image:
  imageType: raw
  baseImage: SLE-Micro.x86_64-5.5.0-Default-GM.raw
  outputImageName: SLEMicro.x86_64--5.5.0-Default-GM-userpass-openstack.raw
operatingSystem:
  kernelArgs:
  - ignition.platform.id=openstack
  users:
  - username: root
    password: foobar


eminguez@lima-default:~> cat eib/_build/combustion/add-users.sh
#!/bin/bash
set -euo pipefail

# Without this, the script will run successfully during combustion, but when /home
# is mounted it will hide the /home used during these user creations.
mount /home









    echo 'root:foobar' | chpasswd -e





```

The password should be encrypted just in case https://sleeplessbeastie.eu/2018/04/09/how-to-securely-change-user-password-using-shell-script/

**Comment by atanasdinov** [comment]
We currently expect the user to provide an [encrypted password](https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#operating-system) but the suggestion is valid that we should be more "user friendly".

**Comment by e-minguez** [comment]
In fact, the -e flag expects encrypted passwords 🗡️

**Comment by jdob** [comment]
I'm fuzzy, is this still an issue? The user provides the encrypted password and we pass it through the system as such. This is not an issue, correct?

**Comment by agracey** [comment]
While I personally don't have an issue with how it currently works, I could see an argument that we change the struct to be:

```
apiVersion: 1.0
image:
  imageType: raw
  baseImage: SLE-Micro.x86_64-5.5.0-Default-GM.raw
  outputImageName: SLEMicro.x86_64--5.5.0-Default-GM-userpass-openstack.raw
operatingSystem:
  kernelArgs:
  - ignition.platform.id=openstack
  users:
  - username: root
    encryptedPassword: $1$6apAbo2R$62Aan6wBsV8crf1p0TiGy.
```

Or, we could add in a way to encrypt the password if it isn't already.
