### ISSUE TITLE
Image type in yaml definition file to be case insensitive

### ISSUE THREAD

**Issue by dbw7** [suse-edge/edge-image-builder#75]
```
apiVersion: 1.0
image:
  imageType: iso
  baseImage: slemicro.iso
  outputImageName: eibimage.iso
  ```
Currently, `imageType` is case sensitive, it should be updated to be case insensitive.
